// promptPacks.js
// Curated prompt data for the shared prompt pipeline. Pure data, no logic --
// see promptLogic.js for the selection/validation functions that consume
// this. spice: 1 = chill, 2 = spicy, 3 = 玩真的 (no-holds-barred).

const WHO_WROTE_THAT = [
  // ---- spice 1: chill ----
  { text: "Your go-to mamak order when someone else is paying", spice: 1 },
  { text: "The most auntie/uncle thing you've done recently", spice: 1 },
  { text: "A food hill you will die on", spice: 1 },
  { text: "The last thing you searched on Shopee", spice: 1 },
  { text: "Your most-used emoji and what it secretly means", spice: 1 },
  { text: "The weirdest thing in your bag/pockets right now", spice: 1 },
  { text: "A skill you claim to have but have never proven", spice: 1 },
  { text: "Your karaoke song when you want to show off", spice: 1 },
  { text: "The most Malaysian sentence you can write", spice: 1 },
  { text: "What you'd tapau if today was your last meal", spice: 1 },
  { text: "Your honest opinion of durian, in one dramatic sentence", spice: 1 },
  { text: "The app you'd be embarrassed to show us your screen time for", spice: 1 },
  { text: "A rule from your childhood home that made no sense", spice: 1 },
  { text: "Your default excuse for being late", spice: 1 },
  { text: "The pettiest reason you've disliked someone", spice: 1 },
  { text: "What your Grab driver rating reason would say", spice: 1 },
  { text: "Describe your driving in three words", spice: 1 },
  { text: "The most useless thing you've bought during a sale", spice: 1 },
  { text: "Your zombie apocalypse role in this friend group", spice: 1 },
  { text: "A smell that instantly takes you back to childhood", spice: 1 },
  { text: "The dish you order to judge a new restaurant", spice: 1 },
  { text: "Your unpopular opinion about CNY", spice: 1 },
  { text: "If your life had a loading screen tip, what would it say?", spice: 1 },
  { text: "The celebrity you irrationally dislike", spice: 1 },

  // ---- spice 2: spicy ----
  { text: "The last white lie you told someone in this room", spice: 2 },
  { text: "Your worst habit that you have zero plans to fix", spice: 2 },
  { text: "The most childish thing you still do in secret", spice: 2 },
  { text: "A time you pretended to be busy to avoid a yumcha invite", spice: 2 },
  { text: "The last thing you cried about (be honest)", spice: 2 },
  { text: "Your most embarrassing search history entry this month", spice: 2 },
  { text: "Something you've done at work/uni you hope your boss never finds out", spice: 2 },
  { text: "The pettiest revenge you've ever taken", spice: 2 },
  { text: "A secret talent nobody in this room knows about", spice: 2 },
  { text: "Your 3am thought that keeps coming back", spice: 2 },
  { text: "The biggest waste of money you've ever committed", spice: 2 },
  { text: "Describe your love life using only a food dish", spice: 2 },
  { text: "The lie you tell your parents most often", spice: 2 },
  { text: "Something you judge people for even though you do it too", spice: 2 },
  { text: "The most desperate thing you've done for free food", spice: 2 },
  { text: "Your actual first impression of the person on your left", spice: 2 },
  { text: "A message you regret sending (paraphrase it)", spice: 2 },
  { text: "The weirdest place you've fallen asleep", spice: 2 },

  // ---- spice 3: 玩真的 ----
  { text: "The biggest red flag you've ever ignored in someone", spice: 3 },
  { text: "Something you've never admitted to anyone in this room", spice: 3 },
  { text: "Your most toxic trait, stated with zero defensiveness", spice: 3 },
  { text: "The real reason your last relationship/situationship ended", spice: 3 },
  { text: "A secret you're keeping for someone else (no names)", spice: 3 },
  { text: "The most money you've lost in one bad decision", spice: 3 },
  { text: "Who in this room would you trust with your phone unlocked, and why not the others?", spice: 3 },
  { text: "The thing you're most insecure about that nobody would guess", spice: 3 },
  { text: "A time you ghosted someone and the actual reason", spice: 3 },
  { text: "The closest you've come to getting caught doing something you shouldn't", spice: 3 },
];

const X_PEOPLE = [
  // ---- spice 1: chill ----
  { text: "Have you ever muted this friend group's chat?", spice: 1 },
  { text: "Have you ever pretended to know a song everyone was singing?", spice: 1 },
  { text: "Have you eaten instant noodles more than 3 times this week?", spice: 1 },
  { text: "Have you ever cried at a Pixar movie?", spice: 1 },
  { text: "Do you secretly think you're the funniest person here?", spice: 1 },
  { text: "Have you ever clapped when a plane landed?", spice: 1 },
  { text: "Do you still sleep with a bolster?", spice: 1 },
  { text: "Have you ever finished someone else's food without asking?", spice: 1 },
  { text: "Have you ever said 'on my way' while still in the shower?", spice: 1 },
  { text: "Do you check your phone within 1 minute of waking up?", spice: 1 },
  { text: "Have you ever forgotten a good friend's birthday?", spice: 1 },
  { text: "Have you ever rewatched an entire drama series more than twice?", spice: 1 },
  { text: "Have you ever talked to yourself out loud in public?", spice: 1 },
  { text: "Do you have more than 3,000 unread emails right now?", spice: 1 },
  { text: "Have you ever eaten cake straight from the fridge with a spoon at 2am?", spice: 1 },
  { text: "Have you ever pretended your phone died to end a conversation?", spice: 1 },

  // ---- spice 2: spicy ----
  { text: "Have you stalked an ex (or their new partner) this month?", spice: 2 },
  { text: "Have you ever pretended to be busy to skip a gathering with people in this room?", spice: 2 },
  { text: "Have you ever cried in a work/uni toilet?", spice: 2 },
  { text: "Have you ever read someone else's messages over their shoulder on the LRT?", spice: 2 },
  { text: "Have you ever lied about your salary?", spice: 2 },
  { text: "Have you ever ghosted someone who did nothing wrong?", spice: 2 },
  { text: "Do you have a crush on someone right now?", spice: 2 },
  { text: "Have you ever screenshot a conversation to complain about it in another chat?", spice: 2 },
  { text: "Have you ever faked being sick to skip work/class this year?", spice: 2 },
  { text: "Have you ever returned something after using it once?", spice: 2 },
  { text: "Have you ever snooped through a partner's or friend's phone?", spice: 2 },
  { text: "Have you ever badmouthed someone in this room to someone else in this room?", spice: 2 },
  { text: "Have you ever pretended to like a gift from someone here?", spice: 2 },
  { text: "Do you owe anyone in this room money right now?", spice: 2 },
  { text: "Have you ever deleted a message right after sending it and hoped they didn't see?", spice: 2 },
  { text: "Have you ever gone through an entire date thinking about someone else?", spice: 2 },

  // ---- spice 3: 玩真的 ----
  { text: "Have you ever been in love with someone in this room?", spice: 3 },
  { text: "Have you ever seriously considered cutting off someone in this room?", spice: 3 },
  { text: "Have you ever lied to your partner about where you were?", spice: 3 },
  { text: "Have you ever kissed someone whose name you didn't know?", spice: 3 },
  { text: "Are you currently hiding something big from your parents?", spice: 3 },
  { text: "Have you ever been the third party in someone's relationship (knowingly or not)?", spice: 3 },
  { text: "Have you ever cried over someone in this room?", spice: 3 },
  { text: "Do you regret something you did at the last gathering of this group?", spice: 3 },
  { text: "Have you ever checked a partner's phone and found something?", spice: 3 },
  { text: "Is there someone you text that this group doesn't know about?", spice: 3 },
];

const PASS_THE_BOMB = [
  // ---- spice 1: chill ----
  { text: "Milo variants or Milo-based drinks", spice: 1 },
  { text: "Things you can order at a mamak", spice: 1 },
  { text: "Pasar malam foods", spice: 1 },
  { text: "Kopitiam drinks (kopi/teh family counts)", spice: 1 },
  { text: "CNY snacks", spice: 1 },
  { text: "Things aunties say at CNY", spice: 1 },
  { text: "Malaysian public holidays", spice: 1 },
  { text: "LRT/MRT station names", spice: 1 },
  { text: "Things in a Malaysian household that are 'for guests only'", spice: 1 },
  { text: "Brands of instant noodles", spice: 1 },
  { text: "Excuses for being late", spice: 1 },
  { text: "Things people fight about in a group chat", spice: 1 },
  { text: "K-drama or C-drama titles", spice: 1 },
  { text: "Mobile games everyone has deleted at least once", spice: 1 },
  { text: "Things you'd find in a mum's plastic-bag drawer", spice: 1 },
  { text: "Durian varieties or things that smell as strong", spice: 1 },
  { text: "Bubble tea toppings or flavours", spice: 1 },
  { text: "Malaysian slang words", spice: 1 },
  { text: "Things that cost RM10 or less at the mamak", spice: 1 },
  { text: "Karaoke songs people always fight over", spice: 1 },
  { text: "Shopee/Lazada impulse buys", spice: 1 },
  { text: "Places to tapau lunch near an office", spice: 1 },
  { text: "Things Malaysians queue for", spice: 1 },
  { text: "Words your grandparents say that you barely understand", spice: 1 },
  { text: "Steamboat ingredients", spice: 1 },
  { text: "Famous Malaysian roads or highways", spice: 1 },

  // ---- spice 2: spicy ----
  { text: "Reasons people ghost someone", spice: 2 },
  { text: "Red flags on a first date", spice: 2 },
  { text: "Lies people tell their parents", spice: 2 },
  { text: "Things people do at work when the boss isn't looking", spice: 2 },
  { text: "Excuses for not paying someone back", spice: 2 },
  { text: "Things people stalk on social media", spice: 2 },
];

const SECRET_MISSIONS = [
  // ---- spice 1: chill ----
  { text: "Get someone to teach you a dance move (any dance)", spice: 1 },
  { text: "Get two different people to high-five you within one minute", spice: 1 },
  { text: "Make someone say 'walao' (you can't say it first)", spice: 1 },
  { text: "Get someone to show you the last photo in their camera roll", spice: 1 },
  { text: "Make two people argue about which state has the best food", spice: 1 },
  { text: "Get someone to check the price of something on Shopee for you", spice: 1 },
  { text: "Convince someone to sing at least one full line of a song", spice: 1 },
  { text: "Take a group selfie where you're the only one not smiling", spice: 1 },
  { text: "Get someone to tell you their phone battery percentage", spice: 1 },
  { text: "Make someone laugh hard enough that they make a sound", spice: 1 },
  { text: "Get someone to agree that durian is overrated OR underrated (your pick)", spice: 1 },
  { text: "Borrow something from someone and return it within 10 minutes", spice: 1 },
  { text: "Get someone to guess your favourite drink — keep going until someone gets it", spice: 1 },
  { text: "Start a conversation about primary school with anyone", spice: 1 },
  { text: "Get someone to stretch or exercise with you", spice: 1 },
  { text: "Make someone check the weather forecast out loud", spice: 1 },
  { text: "Get three people to agree on the best mamak in town", spice: 1 },
  { text: "Get someone to say the name of their first pet", spice: 1 },
  { text: "Convince someone to swap seats with you", spice: 1 },
  { text: "Get someone to show you a meme they saved", spice: 1 },
  { text: "Compliment three different people on three different things", spice: 1 },
  { text: "Get someone to do a 'cheers' with you using non-matching drinks", spice: 1 },

  // ---- spice 2: spicy ----
  { text: "Get someone to tell you about their most recent date", spice: 2 },
  { text: "Get someone to admit the last time they cried", spice: 2 },
  { text: "Get someone to reveal their screen time for one app", spice: 2 },
  { text: "Make someone tell you a secret about a person NOT in this room", spice: 2 },
  { text: "Get someone to say one honest criticism of you, to your face", spice: 2 },
  { text: "Get someone to show you their most-played song this year", spice: 2 },
  { text: "Get two people to admit they've never actually watched a famous movie", spice: 2 },
  { text: "Get someone to tell you how much they spent on food delivery this month", spice: 2 },
  { text: "Get someone to admit a purchase they hid from family/partner", spice: 2 },
  { text: "Get someone to rank three people in this room by cooking skill, out loud", spice: 2 },
];

module.exports = {
  "who-wrote-that": WHO_WROTE_THAT,
  "x-people": X_PEOPLE,
  "pass-the-bomb": PASS_THE_BOMB,
  "secret-missions": SECRET_MISSIONS,
};
